#!/usr/bin/python
import serial
import sys

port = sys.argv[1]
print("Using port: " + port)
ser = serial.Serial(port)
while True:
	line = ser.readline()   # read a '\n' terminated line
	print(line)
ser.close()